version: "3.9"
services:
  support_api:
    build: ./online_support/backend
    privileged: true
    restart: always
    ports:
      - 5000:5000
    command: bash -c "
      uvicorn main:app --host 0.0.0.0 --port 5000
      "
    networks:
      - support

networks:
  support:
    driver: bridge
