# Generated by Django 4.0.6 on 2022-09-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=64, verbose_name='Имя')),
                ('ip_address', models.CharField(max_length=64, verbose_name='IP')),
                ('contacts', models.TextField(verbose_name='Контакты')),
                ('description', models.TextField(verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный репорт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Баг Репорт',
                'verbose_name_plural': 'Баг Репорты',
            },
        ),
    ]
