# Generated by Django 4.0.6 on 2022-09-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='contacts',
            field=models.TextField(blank=True, verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='ip_address',
            field=models.CharField(blank=True, max_length=64, verbose_name='IP'),
        ),
    ]
