# Generated by Django 4.0.6 on 2022-07-18 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('period_type', models.SmallIntegerField(default=0)),
                ('next_notifications', models.DateTimeField(default=datetime.datetime(2022, 7, 19, 21, 51, 41, 202964), verbose_name='Дата следующего напоминания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
        ),
    ]
